blueprint:
  name: Ikea E1743 Trådfri
  description: Blueprint for Ikea E1743 Trådfri switch
  source_url: https://github.com/p11sam1/HA-blueprints/blob/main/ikea-e1743-tr%C3%A5dfri.yaml
  domain: automation
  input:
    remote:
      name: Remote
      description: Choose IKEA remote to use.
      selector:
        device: 
          integration: zha
          manufacturer: IKEA of Sweden
          model: TRADFRI on/off switch
    action_button_up_short:
      name: Up button short press
      description: Action to run on short up button press.
      default: []
      selector:
        action:
    action_button_up_long:
      name: Up button long press
      description: Action to run on long up button press.
      default: []
      selector:
        action:
    action_button_down_short:
      name: Down button short press
      description: Action to run on short down button press.
      default: []
      selector:
        action:
    action_button_down_long:
      name: Down button long press
      description: Action to run on long down button press.
      default: []
      selector:
        action:

trigger:
  platform: event
  event_type: zha_event
  event_data:
    device_id: !input "remote"

action:
  - variables:
      command: "{{ trigger.event.data.command }}"
      cluster_id: "{{ trigger.event.data.cluster_id }}"
      endpoint_id: "{{ trigger.event.data.endpoint_id }}"
      args: "{{ trigger.event.data.args }}"
  - choose:
    - conditions:
        - "{{ command == 'on'}}"
        - "{{ cluster_id == 6 }}"
        - "{{ endpoint_id == 1 }}"
      sequence: !input "action_button_up_short"
    - conditions:
        - "{{ command == 'move_with_on_off'}}"
        - "{{ cluster_id == 8 }}"
        - "{{ endpoint_id == 1 }}"
        - "{{ args == [0, 83] }}"
      sequence: !input "action_button_up_long"
    - conditions:
        - "{{ command == 'off'}}"
        - "{{ cluster_id == 6 }}"
        - "{{ endpoint_id == 1 }}"
      sequence: !input "action_button_down_short"
    - conditions:
        - "{{ command == 'move'}}"
        - "{{ cluster_id == 8 }}"
        - "{{ endpoint_id == 1 }}"
        - "{{ args == [1, 83, 0, 0] }}"
      sequence: !input "action_button_down_long"

mode: restart
max_exceeded: single