blueprint:
  name: Ikea Remote Control N2 Trådfri
  description: Blueprint for Ikea Remote Control N2 Trådfri switch
  source_url: https://github.com/p11sam1/HA-blueprints/blob/main/ikea-remote_control_n2-tradfri.yaml
  domain: automation
  input:
    remote:
      name: Remote
      description: Choose IKEA remote to use.
      selector:
        device: 
          integration: zha
          manufacturer: IKEA of Sweden
          model: Remote Control N2
    action_button_up_short:
      name: Up button short press
      description: Action to run on short up button press.
      default: []
      selector:
        action:
    action_button_up_long:
      name: Up button long press
      description: Action to run on long up button press.
      default: []
      selector:
        action:
    action_button_down_short:
      name: Down button short press
      description: Action to run on short down button press.
      default: []
      selector:
        action:
    action_button_down_long:
      name: Down button long press
      description: Action to run on long down button press.
      default: []
      selector:
        action:
    action_button_left_short:
      name: Left button short press
      description: Action to run on short left button press.
      default: []
      selector:
        action:
#    action_button_left_long:
#      name: Left button long press
#      description: Action to run on long left button press.
#      default: []
#      selector:
#        action:
    action_button_right_short:
      name: Right button short press
      description: Action to run on short right button press.
      default: []
      selector:
        action:
#    action_button_right_long:
#      name: Right button long press
#      description: Action to run on long right button press.
#      default: []
#      selector:
#        action:

trigger:
  platform: event
  event_type: zha_event
  event_data:
    device_id: !input "remote"

action:
  - variables:
      command: "{{ trigger.event.data.command }}"
      cluster_id: "{{ trigger.event.data.cluster_id }}"
      endpoint_id: "{{ trigger.event.data.endpoint_id }}"
      args: "{{ trigger.event.data.args }}"
  - choose:
    - conditions:
          - "{{ command == 'on'}}"
          - "{{ cluster_id == 6 }}"
          - "{{ endpoint_id == 1 }}"
      sequence: !input "action_button_up_short"
    - conditions:
          - "{{ command == 'move_with_on_off'}}"
          - "{{ cluster_id == 8 }}"
          - "{{ endpoint_id == 1 }}"
#          - "{{ args == [0, 83] }}"
      sequence: !input "action_button_up_long"
    - conditions:
          - "{{ command == 'off'}}"
          - "{{ cluster_id == 6 }}"
          - "{{ endpoint_id == 1 }}"
      sequence: !input "action_button_down_short"
    - conditions:
          - "{{ command == 'move'}}"
          - "{{ cluster_id == 8 }}"
          - "{{ endpoint_id == 1 }}"
#          - "{{ args == [1, 83, 0, 0] }}"
      sequence: !input "action_button_down_long"
    - conditions:
          - "{{ command == 'press'}}"
          - "{{ cluster_id == 5 }}"
          - "{{ endpoint_id == 1 }}"
          - "{{ args == [257, 13, 0] }}"
      sequence: !input "action_button_left_short"
    - conditions:
          - "{{ command == 'press'}}"
          - "{{ cluster_id == 8 }}"
          - "{{ endpoint_id == 1 }}"
          - "{{ args == [1, 83, 0] }}"
      sequence: !input "action_button_right_short"

mode: single
max_exceeded: silent